base_url = "https://ethanplant.ca"
title = "Ethan Plant"
default_language = "en_ca"
author = "Ethan Plant"

compile_sass = false

build_search_index = false

generate_feeds = true
feed_filenames = ["rss.xml"]

generate_robots_txt = true

taxonomies = [
    { name = "tags", feed = true }
]

[markdown.highlighting]
light_theme = "catppuccin-latte"
dark_theme = "catppuccin-macchiato"

[extra]
github = "https://github.com/EthanPlant"
mastodon = "https://mastodon.social/@ethanplant"
linkedin = "https://linkedin.com/in/ethanplant"
